### ISSUE TITLE
dismiss last snackbar before show next snackbar

### ISSUE THREAD

**Issue by FabianTerhorst** [zekunyan/TTGSnackbar#1]
Hello,

when i want to show() the next snackbar the last snackbar closed to fast. For example the delay between the 2 shows can be between 10ms and 5s.

**Comment by zekunyan** [comment]
@FabianTerhorst I have removed this feature in the new version. You can try it :）

**Comment by FabianTerhorst** [comment]
@zekunyan thanks, looks good.
