### ISSUE TITLE
Carthage failing with the release of 1.0?

### ISSUE THREAD

**Issue by nadav96** [zekunyan/TTGSnackbar#10]
Hey! While using your library in a new project I've encountered an error while building with Carthage:
`*** Skipped building TTGSnackbar due to the error:
Dependency "TTGSnackbar" has no shared framework schemes`

I was able however to build with version 0.5.3

**Comment by zekunyan** [comment]
I've fixed this issue in the new version 1.0.1. You can try it. Thank you:)
