### ISSUE TITLE
Snackbar on Top

### ISSUE THREAD

**Issue by slown1** [zekunyan/TTGSnackbar#14]
Hello,

 Is there already support for this? If not, how easily is this doable? 
Thank you.

**Comment by zekunyan** [comment]
Show Snackbar at the top of screen?

**Comment by yero007** [comment]
I would also need a snackbar that would display from the top.

Thank you!

**Comment by slown1** [comment]
Yes. On top

**Comment by zekunyan** [comment]
I will develop this feature as soon as possible. 👍

**Comment by slown1** [comment]
Thanks. Thumbs up

**Comment by yero007** [comment]
Thank you!

**Comment by zekunyan** [comment]
@yero007 @slown1 You can try the new version 1.1.0 with `SlideFromTopToBottom` and `SlideFromTopBackToTop` animationType to show snackbar at the top of screen. And i also add `topMargin` property to modify the top margin. :)

**Comment by slown1** [comment]
Great. Thanks a mil.

**Comment by yero007** [comment]
@zekunyan Thanks. :smile:

**Comment by mikeuv** [comment]
Hello, first of all: beautiful pod I have been use it for a while. 
I didn't understand at all, can you help me with some code? 
I'm trying to do something like this: 
snackbar.animationType =  SlideFromTopBackToTop
or 
snackbar.animationType =  "SlideFromTopBackToTop"

Both are incorrect so, how can I do it? 

Thank you!

**Comment by mikeuv** [comment]
Sorry for not being clear: Swift 3.

**Comment by zekunyan** [comment]
@mikeuv You can write it like this:

```
snackbar.animationType = .slideFromTopBackToTop
```
