### ISSUE TITLE
Carthage failing

### ISSUE THREAD

**Issue by nadav96** [zekunyan/TTGSnackbar#18]
Hey man, trying to build the framework in carthage results in error:
`The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **`

Also, I suggest you create a separate branch for all the new changes called swift3, and revert the changes in the master, as the language is not official yet.

**Comment by IsmailHassanein** [comment]
I think that change has been made in the last merge should be in new barnch "swift3" rather than "master"

**Comment by zekunyan** [comment]
It's done :)
