### ISSUE TITLE
Swift 3 issues

### ISSUE THREAD

**Issue by mike9525** [zekunyan/TTGSnackbar#19]
Hi,
I use the Swift3 branch and I have this message during the build:

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly."

**Comment by zekunyan** [comment]
@mike9525 The new version 1.2.1 has fixed this problem. 👍
