### ISSUE TITLE
how to add multiple actions in snackbar?

### ISSUE THREAD

**Issue by sonalipawar** [zekunyan/TTGSnackbar#2]

**Comment by zekunyan** [comment]
@sonalipawar Multiple actions? You mean multi action buttons on the snackbar?

**Comment by sonalipawar** [comment]
Yes.....
plz rpy as possible as.....

**Comment by sonalipawar** [comment]
for eg.... no internet connection ok and try again buttons how to add ths 2 button on snackbar

**Comment by zekunyan** [comment]
@sonalipawar OK, I get it. I will add this feature in the future.

**Comment by mfhenao88** [comment]
@sonalipawar  ya se pueden agregar botones en la vistas customizadas?
