### ISSUE TITLE
[question] Define custom root view

### ISSUE THREAD

**Issue by macszur-mob** [zekunyan/TTGSnackbar#20]
Hi, 

is there any way to define custom root view for snackbar ? In sources I only see hardcoded 
` if let superView = UIApplication.shared.keyWindow {
            superView.addSubview(self)` 
but maybe I'm missing something ?

**Comment by zekunyan** [comment]
It's in the plan. 👍

**Comment by zekunyan** [comment]
@macszur-mob The new version 1.2.2 has `containerView`  which can customize the snackbar super view. You can try it.
