### ISSUE TITLE
Animation Time

### ISSUE THREAD

**Issue by percyPolymorph** [zekunyan/TTGSnackbar#21]
When the animation time is increased the snackbar does not dismiss when dismiss is called from an action on iOS 10. When the animation duration is set to like 1. then it is still okay, but anything more than that makes it unresponsive.

**Comment by zekunyan** [comment]
Can you post your code? I can not reproduce this situation.

**Comment by percyPolymorph** [comment]
let snackbar = TTGSnackbar.init(message: "Message", duration: .long, actionText: "Dismiss", messageFont: UIFont(name: "ExpertSans-Regular", size: 14)!, actionTextFont: UIFont(name: "ExpertSans-Regular", size: 14)!) { (snackbar) in
            
            snackbar.dismiss()
        }
        
        snackbar.actionTextColor = UIColor(netHex: 0x00AEEF)
        snackbar.cornerRadius = 0
        snackbar.leftMargin = 0
        snackbar.rightMargin = 0
        snackbar.bottomMargin = 0
        
        snackbar.animationType = .slideFromBottomBackToBottom
        snackbar.animationDuration = 4

        
        snackbar.show()

**Comment by percyPolymorph** [comment]
When the animation duration is changed to 1. It feels more responsive. Like you cant dismiss while the animation is executing. But this wasn't an issue on swift 2.

**Comment by zekunyan** [comment]
When you want to dismiss snackbar manually you should use `.forever` for the `duration` option.
And the new version 1.2.3 has fixed the animation problem. 👍
