### ISSUE TITLE
height property?

### ISSUE THREAD

**Issue by mugcookie** [zekunyan/TTGSnackbar#25]
Hello.
In your document, there is `height: CGFloat`  for customization. but I can't find it. (I installed TTGSnackbar by CocoaPods)

I tried this code before call show() function,
`mySnackbar.frame.size.height = 60`
but it still have min height, 44px.

I tried also using customContentView, but it didn't work... I create a UIView by code, not xib. 

How to increase snackbar's height?

**Comment by zekunyan** [comment]
I am sorry that the `height` property has been removed in the new version. If you want to increase the height, you can increase the `contentInset`. 

If you use the `customContentView`, the `height` is calculated like this:

```
 if let customContentView = snackbar.customContentView {
            height = customContentView.frame.size.height + snackbar.contentInset.top + snackbar.contentInset.bottom
}
```

**Comment by mugcookie** [comment]
@zekunyan  Thanks! It works perfect.
