### ISSUE TITLE
Longer action text not readable

### ISSUE THREAD

**Issue by vonox7** [zekunyan/TTGSnackbar#26]
The action button does not resize when using longer action buttons. This is especially a problem when localising the app to languages like german (words tend to be much longer than in english)
The [material guidelines](https://material.io/guidelines/components/snackbars-toasts.html) show even snackbars with longer action buttons.

Expected behaviour: Don't make the action button text smaller but increase the buttons width.

Please either increase the maxWidth or allow the application developer to increase the maxWidth.

![image](https://cloud.githubusercontent.com/assets/621501/21955492/9723eff8-da6c-11e6-9d16-b7ecf11cbe3a.png)

**Comment by zekunyan** [comment]
The new version `1.5.0` has added `actionMaxWidth` and `actionTextNumberOfLines ` two properties. They may solve your problem. :)
