### ISSUE TITLE
expose snackbarMinHeight as a public var

### ISSUE THREAD

**Issue by murad1981** [zekunyan/TTGSnackbar#28]
it would be nice if the height of the snacker is configurable through a public property, for now, to change the height I ave to change the snackbarMinHeight private variable.

**Comment by kuyazee** [comment]
You could also just use a `customContentView` instead if you want.

**Comment by zekunyan** [comment]
@murad1981 snackbarMinHeight = 44 is for "Provide ample touch targets for interactive elements. Try to maintain a minimum tappable area of 44pt x 44pt for all controls." https://developer.apple.com/ios/human-interface-guidelines/visual-design/adaptivity-and-layout/
