### ISSUE TITLE
 actionBlock with custom function calling

### ISSUE THREAD

**Issue by naga1985** [zekunyan/TTGSnackbar#32]
Hi 
I am new to the swift , snack bar is working fine my app,
I want call the the Custom function using  Action Block 

let snackbar = TTGSnackbar(message: "Attendance Update !",
                               duration: .long,
                               actionText: "SEND",
                              
                               actionBlock: {
                                    (snackbar) in
                                
                                uncheck()
                                
                                print("snack bar Action")
                                
    })
    
    func uncheck()
    {

        print("snackbar uncheck function")
        snackbarCount -= 1
        checkSnackBar()
    }

this is my action block code I want access the uncheck function using Action Block .pls help me 
how to access the uncheck function

**Comment by zekunyan** [comment]
Use self.uncheck()
