### ISSUE TITLE
Center the text without using a CustomView

### ISSUE THREAD

**Issue by bernaferrari** [zekunyan/TTGSnackbar#34]
Is there a way of centering the text field without using a CustomView? While this looks simple enough, I  haven't found it nowhere in the documentation.
Thanks!

**Comment by zekunyan** [comment]
This feature will be added in the next version.

**Comment by zekunyan** [comment]
@bernaferrari 
```
snackbar.messageTextAlign = .center
```

**Comment by bernaferrari** [comment]
Thanks!!!
