### ISSUE TITLE
XCode 9, Objective-C, 1.6.0. Compile-time errors

### ISSUE THREAD

**Issue by zykis** [zekunyan/TTGSnackbar#43]
I knew nothing about Swift, so if you could point me out, why 
`No visible @interface for 'TTGSnackbar' declares the selector 'show'`
error appears. Guess it's Extension namespace visibility problems. Any idea how to fix it?
Everything works just fine before i moved out to XCode 9.0 and updated Pod.
`[[TTGSnackbar alloc] initWithMessage:message duration:TTGSnackbarDurationShort];`
Also show the same type of error

**Comment by zekunyan** [comment]
You can check the latest commit. I have updated the OC Example Demo.

**Comment by zykis** [comment]
Yeah, just have seen that. Still, `/ExampleObjc/TTGSnackbarObjcExample/Pods/TTGSnackbar/README.md ` in Swift. Are you sure that ExampleObjC is running fine? Can't check it untill evening.

**Comment by zykis** [comment]
I've ended up making my AlertView, based on your sources in pure Objective-c. Sorry, didn't test an Objective-C example
