### ISSUE TITLE
49 Errors when compiling it with Swift4 Ios11, Xcode 9

### ISSUE THREAD

**Issue by siyavash4812** [zekunyan/TTGSnackbar#44]
I have updated it to the last version but i have around 49 errors! Can you please have a look at this?

<img width="349" alt="screen shot 2017-09-28 at 13 50 57" src="https://user-images.githubusercontent.com/22658677/30967409-1eed02c4-a454-11e7-93f3-fdff774809b4.png">

<img width="344" alt="screen shot 2017-09-28 at 13 51 09" src="https://user-images.githubusercontent.com/22658677/30967433-2f759412-a454-11e7-8248-b67db2b6b997.png">

**Comment by zykis** [comment]
I've resolved a lot of compile errors by setting up SWIFT version to 4.0 in Pods build settings. Try it out, if it's 3.0 or something

**Comment by zekunyan** [comment]
@zykis Great work~
@siyavash4812 The latest version is for Swift 4.0 :)

**Comment by siyavash4812** [comment]
I uninstalled and installed it again and its working perfectly fine :D . Btw is there anyway to change the size of the icon?

**Comment by zekunyan** [comment]
@siyavash4812 I will think about this feature in the next version. For now you can write your own custom content view to customize the UI.
