### ISSUE TITLE
Handling iPhone X bottom offset

### ISSUE THREAD

**Issue by shaysemireg** [zekunyan/TTGSnackbar#46]
Snackbars render outside of the "safe area" that allow UI elements to not conflict or become obscured by iPhone X UI elements. This can result in the iPhone X's bottom home bar rendering on top of the Snackbar's content.

There are a few workarounds to deal with this in our own apps. We can increase or assign the bottomOffset property of the snackbar manually, depending on whether the device is an iPhone X. However, this is not ideal because Apple does not offer a clean way of detecting the iPhone X screen type, the offset will have to be hardcoded, and the code is not forward compatible with other screen types.

An alternative would be for TTGSnackbar to use safeArea in the bottom constraint (or offer it as a configuration option). Here is a basic example of how this could be accomplished:

https://github.com/shaysemireg/TTGSnackbar/commit/7216df3d80cada2be6d4d6569f206238d479c3fd

**Comment by zekunyan** [comment]
Great work! You can push a PR

**Comment by zekunyan** [comment]
@shaysemireg  Still some bug when dismiss on iPhoneX. I will fix this later and push a new release.

**Comment by zekunyan** [comment]
The new version 1.7.1 has released.
