### ISSUE TITLE
Not showing loading indicator for forever duration

### ISSUE THREAD

**Issue by jagajithmk** [zekunyan/TTGSnackbar#50]
The loading indicator is not showing in Swift 4.

**Comment by zekunyan** [comment]
Show me your code.

**Comment by jagajithmk** [comment]
let loadingSnackbar = TTGSnackbar(message: "\n"+text+"\n", duration: .forever)
    loadingSnackbar.messageTextFont = Constants.Fonts.alertFont
    loadingSnackbar.backgroundColor = Constants.Color.alertBackground
    loadingSnackbar.cornerRadius = 8
    loadingSnackbar.leftMargin = 8
    loadingSnackbar.rightMargin = 8
    loadingSnackbar.bottomMargin = 8
    loadingSnackbar.show()

**Comment by zekunyan** [comment]
I will check this.
