### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by AlirezaAkbarix** [zekunyan/TTGSnackbar#51]
How is it possible to make Snackbar RTL?

**Comment by JhonnyTawk** [comment]
Create a function to check if the view is forceRighToLeft Use : 
`return appearance().semanticContentAttribute == .forceRightToLeft`
And then check if it is isRTL . use :   `snackbar.messageTextAlign = .right`
otherwise  `snackbar.messageTextAlign = .left`

**Comment by zekunyan** [comment]
The new version will support RTL
