### ISSUE TITLE
Snackbar crashes when shown on some pushed views 

### ISSUE THREAD

**Issue by sajjad-tintash** [zekunyan/TTGSnackbar#54]
Crashes at:  superView.addConstraint(leftMarginConstraint!) in show()

**Comment by zekunyan** [comment]
Some detail code ?

**Comment by sajjad-tintash** [comment]
When some custom animation is being shown on a UIWindow in the app for some time duration, if I try to display snackbar notification due to some reason (a server error message or whatever) and that animation window is removed meanwhile, the snackbar crashes at this line: 

`superView.addConstraint(leftMarginConstraint!)`

For this specific case superview becomes nil. In my opinion, when the snackbar is used in a way that a lot of notifications are to be displayed using a queue or stack(as its being done in my app), the best way would be to use guard statement at both points, while creating and while displaying the bar. 

However, I fixed this issue, a couple of months back, by handling specific cases and using guard let and if let statements in Snackbar source code file.
