### ISSUE TITLE
Custom duration

### ISSUE THREAD

**Issue by kelvinleague** [zekunyan/TTGSnackbar#59]
Hello,

It seems currently that the snackbar duration is tied to an integer enum. 

Would it be possible to create a new initializer that takes in an int as the duration property rather than tying it strictly to an enum? That way we are not restricted to 1, 3, 5 or forever.

Thanks!

**Comment by zekunyan** [comment]
@kelvinleague You can do it by this: 
```Swift
snackbar.duration = TTGSnackbarDuration(rawValue: 10)!
```

**Comment by zekunyan** [comment]
@ManueGE You can do it by `snackbar.duration = TTGSnackbarDuration.init(rawValue: 5)!`

**Comment by MockinMan** [comment]
> @ManueGE You can do it by `snackbar.duration = TTGSnackbarDuration.init(rawValue: 5)!`

It will indeed work with 5, because `enum` has `case long = 5`, but it won't work with any other custom value, unfortunately.
Can this be improved, do you still work on this library?

**Comment by zekunyan** [comment]
@MockinMan I will add this feature tomorrow.
