### ISSUE TITLE
Cannot center the snackbar in the view horizontally

### ISSUE THREAD

**Issue by Daksh14** [zekunyan/TTGSnackbar#60]
I cannot center the snack bar by the following code
```swift
snackbar.centerXAnchor.constraint(equalTo: snackbar.centerXAnchor).isActive = true
```

**Comment by Daksh14** [comment]
I was able to do it by doing 
```swift
snackbar.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
```
Closing this issue.

**Comment by Daksh14** [comment]
I ran into a problem while centering the snack bar. I use a class to invoke the snackbar like this
```swift
import UIKit
import TTGSnackbar

class SnackBarInit {
    let msg :String
    let snackbar :TTGSnackbar
    let dontJustGo :Bool
    init(msg:String,dontJustGo:Bool = false) {
        self.msg = msg

        self.dontJustGo = dontJustGo
        if dontJustGo {
            self.snackbar = TTGSnackbar(message: msg, duration: .forever)
        } else {
            self.snackbar = TTGSnackbar(message: msg, duration: .short)
        }
    }
    func ShowSnack() -> TTGSnackbar {
        snackbar.onTapBlock = { snackbar in
            snackbar.dismiss()
        }
        snackbar.widthAnchor.constraint(equalToConstant: 250).isActive = true
        snackbar.actionMaxWidth = CGFloat(1.00)
        snackbar.messageTextAlign = .center
        snackbar.bottomMargin = 50
        snackbar.animationType = .slideFromBottomToTop
        snackbar.onSwipeBlock = { (snackbar, direction) in
            
            // Change the animation type to simulate being dismissed in that direction
            if direction == .right {
                snackbar.animationType = .slideFromLeftToRight
            } else if direction == .left {
                snackbar.animationType = .slideFromRightToLeft
            } else if direction == .up {
                snackbar.animationType = .slideFromTopBackToTop
            } else if direction == .down {
                snackbar.animationType = .slideFromTopBackToTop
            }
            
            snackbar.dismiss()
        }
        snackbar.show()
        return snackbar
    }
}
```
Now, as I need to center it by calculating from the view.  You see first I call `snackbar.show()` and then I do `return snackbar` and then I change anchors and constraints like this

```swift
if passwordValue!.count <= 4 {
            let instance = SnackBarInit(msg: "The password needs to be at least 4 words long")
            let snack = instance.ShowSnack()
            goodPassword = false
            TapticEngine.notification.feedback(.error)
            snack.translatesAutoresizingMaskIntoConstraints = false
            snack.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
            snack.bottomAnchor.constraint(equalTo:view.bottomAnchor,constant: -50).isActive = true
} else {
            goodPassword = true
}

```
This crashes my application by saying

>  Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x281966780 "UIView:0x143e68e90.top"> and <NSLayoutYAxisAnchor:0x2819664c0 "UIButton:0x143e1a180'Tags'.top"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.'

The reason for this dangerous crash is that I'm doing these constraints changes before the snack bar is in the actual view. <br> Now here is the actual bug. After `snackbar.show()` my code runs but still the snackbar is not in the view. <br>Does anyone have a solution to this problem?

**Comment by zekunyan** [comment]
It's not recommended to add extra Autolayout constrains to the Snackbar, because each Snackbar instance has its own constraints to its "proper" superView. 

Maybe in the future i will add something like "position" in Snackbar's configuration.

**Comment by Daksh14** [comment]
Okay so do you have any idea how do I center the snack bar in the view?

**Comment by zekunyan** [comment]
There is no proper way to do so for the current version. Sorry.
