### ISSUE TITLE
Margins and corder radius

### ISSUE THREAD

**Issue by RuslanPatyk** [zekunyan/TTGSnackbar#7]
Please, make enum that configures the appearance of snackbar: whether it rounds it's corners or not, whether uses 4 points margins or 0 point margins, like it is implemented in Google's Inbox. Thank you

**Comment by zekunyan** [comment]
@RuslanPatyk I will update it in a few days.

**Comment by zekunyan** [comment]
@RuslanPatyk Now you can configure the cornerRadius and margins in the latest version.
