### ISSUE TITLE
Failed to get the superview 

### ISSUE THREAD

**Issue by ruangchupa** [zekunyan/TTGSnackbar#78]
Hey there,

I got a problem when getting the super view so I always got this `fatalError("TTGSnackbar needs a keyWindows to display.")` error.

I found out that this line which was relevant with the problem:
`if let superView = containerView ?? UIApplication.shared.delegate?.window  ?? UIApplication.shared.keyWindow` (https://github.com/zekunyan/TTGSnackbar/blob/master/TTGSnackbar/TTGSnackbar.swift#L565)

Turned out that my `containerView` and `UIApplication.shared.delegate?.window` was nil and Swift always failed to understand that my `UIApplication.shared.delegate?.window` was nil.

So it was always assigning the `nil` `UIApplication.shared.delegate?.window` to `superview` so I was always proceeded to the error block.

I just changed the relevant line to this:
`if let superView = containerView ?? (UIApplication.shared.delegate?.window ?? nil) ?? UIApplication.shared.keyWindow {`

And now everything works fine. Is it only me or is it problem for everyone? I'm using Xcode 11.3.1 and Swift 5.

**Comment by zekunyan** [comment]
The new version 1.10.0 has fixed this. Thanks~
