### ISSUE TITLE
Unable to set height lower than 44

### ISSUE THREAD

**Issue by klwoon** [zekunyan/TTGSnackbar#8]
When I set height lower than 44 it defaults to 44, is it possible to change this behaviour?
And thanks for the great library, love it!

**Comment by zekunyan** [comment]
According to the https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/LayoutandAppearance.html **"Make it easy for people to interact with content and controls by giving each interactive element ample spacing. Give tappable controls a hit target of about 44 x 44 points."**. 
So i set a limitation to the `height` like this:
```
/// Height: [44, +]. Default is 44
public var height: CGFloat = 44 {
    didSet {
        if height < 44 {
            height = 44
        }
    // ...
    }
}
```
