### ISSUE TITLE
Fatal error: TTGSnackbar needs a keyWindows to display.

### ISSUE THREAD

**Issue by R-Ashh** [zekunyan/TTGSnackbar#81]
in iOS 13 snackbar.show() method will run into this issue

Thread 1: Fatal error: TTGSnackbar needs a keyWindows to display. - Google Search

**Comment by zekunyan** [comment]
Can you show me your code ?

**Comment by subhajitregor** [comment]
@zekunyan I was facing the same issue, made a fix for that, can you check the PR.

**Comment by R-Ashh** [comment]
> Can you show me your code ?

sure here's the code example that will crash

```
let snackbar = TTGSnackbar(message: response.value?.errorMessage ?? "Something went wrong, please try again later!", duration: .short)
                    snackbar.show()
```

**Comment by zekunyan** [comment]
The new version 1.10.0 has fixed this. Thanks~
