### ISSUE TITLE
issue with ios 13

### ISSUE THREAD

**Issue by seraph3b** [zekunyan/TTGSnackbar#83]
it seems that snackbar doesn't appear on ios 13, i've removed this line on show function:
       currentWindow = UIApplication.shared.windows.filter({$0.windowScene?.activationState == .foregroundActive}).first! (ine 584)
also replacing with  UIApplication.shared.windows.first { $0.isKeyWindow }
works fine

**Comment by zekunyan** [comment]
@seraph3b It works fine for me. Please show me your demo code thanks.

**Comment by seraph3b** [comment]
project target is ios 10
running on a ios 13 device
in AppDelegate ->
let homeVC = sb.instantiateViewController(withIdentifier: "home") // home is the identifier in storyboard
initialViewController = UINavigationController(rootViewController: homeVC)
window?.rootViewController = initialViewController

when home controller is loaded I have a button, on tap ->
let snackbar = TTGSnackbar(message: "TTGSnackbar !", duration: .short)
snackbar.show() // as sample but it's the same also on customized snackbar

on show function I think than UIApplication.shared.windows.filter({$0.windowScene?.activationState == .foregroundActive}).first! is not the window in foreground.
thanks for your support

**Comment by zekunyan** [comment]
@seraph3b The new version 1.10.1 may fix this problem.
