### ISSUE TITLE
Updated to 1.10.0 now crashes (sometimes) on startup...

### ISSUE THREAD

**Issue by adamjack** [zekunyan/TTGSnackbar#84]
I (mindlessly) updated pods yesterday, did a build, and released my application to TestFlight. I made a minor change, so just wanted to see what testing did.

My TTGSnackbar updated (I believe) from:

    TTGSnackbar 1.9.2 -> 1.10.0

... and it has started crashing on a TTGSnackbar I raise (from main thread) on close to app startup (after a network call.) It is intermittent .. so timing related. I don't have much detail (sadly) 'cos Xcode hates me, and has never given me a decent stack trace. All I get I will try to share as attachments.

Both reporters are on iOS 13.3.1.

I am going to revert to 1.9.2 to see if the problem goes away. I'll report results here.
<img width="272" alt="Stack1" src="https://user-images.githubusercontent.com/105598/76877295-c9200e80-6838-11ea-9165-4fb690ef9a55.png">
<img width="691" alt="Stack2" src="https://user-images.githubusercontent.com/105598/76877309-ce7d5900-6838-11ea-83c7-3647315fb76e.png">

**Comment by adamjack** [comment]
I say intermittent, it may have been one time only. Both reports seem to say it only happened once, and hasn't happened since. They may have launched from TestFlight, maybe, I don't know if or how that might make a difference.

**Comment by zekunyan** [comment]
@adamjack You can check 1.10.1.

**Comment by zekunyan** [comment]
@adamjack I can not get any useful information from your Xcode Crash threads calls image. Can you please provide more detail ?

**Comment by adamjack** [comment]
I wish I could give more information. I seem to have angered Xcode many moons ago 'cos I can never get a decent stack trace out of it. I will try 1.10.1 however I am stuck on a poor link and uploads to ITC fail from here. I'll upload when I can.

Does it make sense that launching from TestFlight might have some impact, or is that a long shot? I don't know if TestFlight messes with the startup timing or view hierarchy or something.

I can build another and ask my testers to try it out. I cannot seem to reproduce, but they can.

**Comment by adamjack** [comment]
Hmm, I did just reproduce it. I got a 13.3.1 iPad and ran the app from TestFlight. TestFlight (the first time) appears to automagially pop-up a "What to Test" model ... and I suspect that somehow that is interacting negatively with the TTGSnackbar code. It could be coincidence but if I load the app from desktop icon or from TestFlight (but after the one time pop-up) it does not crash.

**Comment by adamjack** [comment]
I tried building a sample app to attempt to reproduce, and used version 1.10.0 with 

    https://github.com/adamjack/SnackbarTest

Something as simple as :

  override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        let snackbar = TTGSnackbar(message: "Testing Testing 1 2 3 Testing...", duration: TTGSnackbarDuration.forever)
        snackbar.show()
    }

and it immediately crashed here:

       // Fetching window for iOS 13
        if #available(iOS 13.0, *) {
            currentWindow = UIApplication.shared.windows.filter({$0.windowScene?.activationState == .foregroundActive}).first!
        }

It seems to crash slightly differently with 1.10.1:

   Unexpectedly found nil while unwrapping an Optional value: file

Retrying (after I checked into GitHub, re-checked out, not sure what is different) I get: TTGSnackbar.swift line 669 

              fatalError("TTGSnackbar needs a keyWindows to display.")

1) Is my test invalid?
2)Does this really crash my app in failure ... that is a tad impolite for a library. :-)

Thanks, and if I can get past this I'll work on trying to figure out the (potential) problem with the modal, or whatever else is occurring with TestFlight.

**Comment by adamjack** [comment]
@zekunyan If you get time, please let me know if this sample crashes for you, and maybe if it is somehow an invalid test. I started it so I could raise a modal to try to reproduce the TestFlight modal, but haven't gotten that far, it is crashing with 10.0.0 and 10.0.1 before I get to that.

**Comment by zekunyan** [comment]
@adamjack Thank you for your issue. I fix this crash in the new version 1.10.2.

**Comment by adamjack** [comment]
@zekunyan Thanks, I tried 1.10.2 and I see you debugPrint so no crash, but also no Snackbar.

Can you tell me why my sample might be an invalid test, that you skip raising a Snackbar? This isn't one of my use cases, but it is pretty closes to it.

**Comment by zekunyan** [comment]
@adamjack Maybe your app does not have a valid UIWindows when your controller viewDidLoad called.
