### ISSUE TITLE
Snackbars on iPhone X (or newer) devices look oddly placed

### ISSUE THREAD

**Issue by GoannaGuy** [zekunyan/TTGSnackbar#89]
Apps on newer devices that are designed to extend under the iPhone X and newer "Swipe up for Home" area that use TTGSnackbar may look strange, since the TTGSnackbar does not seem to attach to the actual bottom of the screen. A gap remains below the snackbar, where the apps's content shows through. 

TTGSnackbar should have an option to not honor the Safe Area Layout Guide for use cases where the design already takes the safe area into account.

Pull Request: #88

**Comment by zekunyan** [comment]
Thank you for your PR :)

**Comment by zekunyan** [comment]
I will check this and release it as soon as possible.
