### ISSUE TITLE
Obj-c Compatibility?

### ISSUE THREAD

**Issue by arvindkumar-gr** [zekunyan/TTGSnackbar#9]

**Comment by zekunyan** [comment]
@arvindkumar-gr I am working on it. :)

**Comment by zekunyan** [comment]
@arvindkumar-gr The new version 0.5.3 is compatible with Objc. Here is the example: [TTGSnackbar/tree/master/Example-Objc](https://github.com/zekunyan/TTGSnackbar/tree/master/Example-Objc)

**Comment by arvindkumar-gr** [comment]
@zekunyan Thank you! will check it out. 👍

**Comment by zykis** [comment]
well, the reference is dead

**Comment by zekunyan** [comment]
@zykis Check this: https://github.com/zekunyan/TTGSnackbar/tree/master/ExampleObjc/TTGSnackbarObjcExample

**Comment by zykis** [comment]
Oh, thanks!
Was able to embed it straight away into my objective-c project.Clean and easy. Works perfect!
